project:
  type: website
  output-dir: _output
  pre-render: prepare.R
  post-render: make_r_files.R

metadata-files:
  - _website.yml

format:
  html:
    theme:
      - simplex
      - brand
    css: styles.css
    toc: true
    df-print: kable
