---
title: "About"
---

# Acerca de este documento

::: {.callout-important}
Este material est谩 en desarrollo. 
:::


## Ensayos disponibles

### И Ensayos en estaciones experimentales

-  [Ensayo con testigos apareados](Testigos_Apareados.qmd):  
  Evaluaci贸n del efecto de una pr谩ctica de manejo en ambientes contrastantes, utilizando modelos mixtos con y sin correlaci贸n espacial.

-  [Ensayo de cultivares de trigo (DBCA)](Trigo_DBCA.qmd):  
  Comparaci贸n de cultivares de trigo bajo un dise帽o en bloques completos al azar, con ajuste de modelos mixtos y evaluaci贸n de estructuras espaciales de error.

###  Ensayos en campos de productores (OFE)

-  [OFE - Regresi贸n](MLM_CorrEsp_OFE_Reg.qmd):  
  Evaluaci贸n del efecto de tratamientos fosforados en distintas zonas del lote. Se ajustan modelos mixtos con y sin correlaci贸n espacial, y se comparan las medias ajustadas por ambiente.

- Л [OFE - Clasificaci贸n](MLM_CorrEsp_OFE_Clasif.qmd):  
  An谩lisis de la respuesta a distintas dosis de nitr贸geno en cuatro zonas de manejo. Se ajustan modelos polin贸micos y se predicen las dosis 贸ptimas de N por zona, considerando la estructura espacial del error.

## Objetivo

Brindar ejemplos reproducibles de an谩lisis de ensayos que integren:

- Estad铆stica descriptiva
- Modelos lineales mixtos
- Modelizaci贸n espacial

---

## Contacto

Para dudas o sugerencias, pod茅s contactarnos a trav茅s de [LinkedIn](https://www.linkedin.com/in/ppaccioretti/) o v铆a correo institucional.
